from enum import Enum

class AgentName(Enum):
    NUTRITION = "nutrition"
    NUTRITION_TIP = "nutrition-tip"
    NUTRITION_TEXT_LOGGING = "nutrition-text-logging"
    NUTRITION_IMAGE_LOGGING = "nutrition-image-logging"
    NUTRITION_LABEL_IMAGE_LOGGING = "nutrition-label-image-logging"
    NUTRITION_INSIGHTS = "nutrition-insights"
    MENSTRUATION_PERSONA_UPDATE = "menstruation-persona-update"
    PREGNANCY_PERSONA_UPDATE = "pregnancy-persona-update"


class PlanType(Enum):
    ADDED_SUGAR_RESET = "added_sugar_reset"
    BALANCED_BLOOD_SUGAR = "balanced_blood_sugar"
    HORMONE_SUPPORT = "hormone_support"
    PCOS_METABOLIC_SUPPORT = "pcos_metabolic_support"
    PCOS_INFLAMMATION_GUT = "pcos_inflammation_gut"
    CYCLE_SYNC_NATURAL = "cycle_sync_natural"
    PERIOD_PAIN_SUPPORT = "period_pain_support"
    PMS_BLOATING_WATER_RETENTION = "pms_bloating_water_retention"
    IRON_SUPPORT = "iron_support"
    FERTILITY_SUPPORT = "fertility_support"
    PRECONCEPTION_NUTRIENT_OPTIMIZATION = "preconception_nutrient_optimization"
    PREGNANCY_T1_SUPPORT = "pregnancy_t1_support"
    PREGNANCY_T2_GROWTH = "pregnancy_t2_growth"
    PREGNANCY_T3_PREPARATION = "pregnancy_t3_preparation"
    GESTATIONAL_DIABETES_SUPPORT = "gestational_diabetes_support"
    POSTPARTUM_RECOVERY = "postpartum_recovery"
    BREASTFEEDING_SUPPORT = "breastfeeding_support"
    THYROID_NUTRITION_SUPPORT = "thyroid_nutrition_support"
    SUSTAINABLE_WEIGHT_MANAGEMENT = "sustainable_weight_management"
    MENOPAUSE_STRENGTH_BALANCE = "menopause_strength_balance"
    ENDOMETRIOSIS_INFLAMMATION_SUPPORT = "endometriosis_inflammation_support"
    EGG_HEALTH_ANTIOXIDANT = "egg_health_antioxidant"
    PMS_MOOD_CRAVING_SUPPORT = "pms_mood_craving_support"
    CYCLE_REGULARITY_SUPPORT = "cycle_regularity_support"
    STRESS_SLEEP_RESET = "stress_sleep_reset"
    GUT_COMFORT_RESET = "gut_comfort_reset"
    GLOW_SKIN_HEALTH = "glow_skin_health"

class AgentModuleEnum(Enum):
    NUTRITION = "nutrition"
    PERSONA = "persona"